#pragma once

#ifdef AUDIO_ENABLE
#define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#define MIDI_BASIC

#define ENCODER_RESOLUTION 4

#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define LAYER_LOCK_IDLE_TIMEOUT 10000
#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 120000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 22

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 1

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 6

#define SERIAL_NUMBER "agKMo/wOEn5j"
#define LAYER_STATE_32BIT
#define COMBO_COUNT 4

#define RGB_MATRIX_STARTUP_SPD 60

// Custom

#undef LEADER_TIMEOUT
// #define LEADER_NO_TIMEOUT
// #define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 1000
// #define QUICK_TAP_TERM 50
