#pragma once

#ifdef AUDIO_ENABLE
#define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#define MIDI_BASIC

#define ENCODER_RESOLUTION 4

#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define LAYER_LOCK_IDLE_TIMEOUT 10000
#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "agKMo/jZOj7x"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 1

#define RGB_MATRIX_STARTUP_SPD 60

