CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NO_USB_STARTUP_CHECK = yes
ORYX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
LAYER_LOCK_ENABLE = yes



# Custom
REPEAT_KEY_ENABLE = yes
LEADER_ENABLE = yes
