name: Auto Build Layout

on:
  push:
    paths:
      - "5qJbe/**"
      - "agKMo/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      layout5qJbe: ${{ steps.filter.outputs.layout5qJbe }}
      agKMo: ${{ steps.filter.outputs.e5WnW }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Shallow clone for faster checkout

      - name: Filter changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            layout5qJbe:
              - '5qJbe/**'
            agKMo:
              - 'agKMo/**'

  build-moonlander-5qJbe:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.layout5qJbe == 'true' }}
    uses: ./.github/workflows/fetch-and-build-layout.yml
    with:
      layout_id: 5qJbe
      layout_geometry: moonlander

  build-planck-agKMo:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.agKMo == 'true' }}
    uses: ./.github/workflows/fetch-and-build-layout.yml
    with:
      layout_id: agKMo
      layout_geometry: planck_ez/glow
